version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Show environment variable
          command: echo "${search_server_url}"
  deploy:
    working_directory: ~/repo
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Show environment variable
          command: echo "${search_server_url}"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
          requires:
            - build
          filters:
            branches:
              only: master