version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: echo "${search_server_url}"
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
          filters:
            branches:
              only: master